// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: core.sql

package coredb

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	decimal "github.com/shopspring/decimal"
)

const createAuditEvent = `-- name: CreateAuditEvent :one
INSERT INTO audit_events (
    event_type,
    severity,
    symbol,
    message,
    payload
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, event_type, severity, symbol, message, payload, created_at
`

type CreateAuditEventParams struct {
	EventType string          `json:"event_type"`
	Severity  string          `json:"severity"`
	Symbol    string          `json:"symbol"`
	Message   string          `json:"message"`
	Payload   json.RawMessage `json:"payload"`
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRowContext(ctx, createAuditEvent,
		arg.EventType,
		arg.Severity,
		arg.Symbol,
		arg.Message,
		arg.Payload,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.Severity,
		&i.Symbol,
		&i.Message,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const createOrderExecution = `-- name: CreateOrderExecution :one
INSERT INTO order_executions (
    order_plan_id,
    exchange_order_id,
    client_order_id,
    status,
    filled_quantity,
    avg_price,
    fee_usdt,
    raw_response,
    error_message,
    submitted_at,
    filled_at,
    failed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    CASE WHEN $4 IN ('submitted', 'filled') THEN now() ELSE NULL END,
    CASE WHEN $4 = 'filled' THEN now() ELSE NULL END,
    CASE WHEN $4 = 'failed' THEN now() ELSE NULL END
)
ON CONFLICT (order_plan_id) DO UPDATE SET
    updated_at = now()
RETURNING id, order_plan_id, exchange_order_id, client_order_id, status, filled_quantity, avg_price, fee_usdt, raw_response, error_message, submitted_at, filled_at, failed_at, created_at, updated_at
`

type CreateOrderExecutionParams struct {
	OrderPlanID     int64           `json:"order_plan_id"`
	ExchangeOrderID sql.NullString  `json:"exchange_order_id"`
	ClientOrderID   string          `json:"client_order_id"`
	Status          string          `json:"status"`
	FilledQuantity  decimal.Decimal `json:"filled_quantity"`
	AvgPrice        decimal.Decimal `json:"avg_price"`
	FeeUsdt         decimal.Decimal `json:"fee_usdt"`
	RawResponse     json.RawMessage `json:"raw_response"`
	ErrorMessage    sql.NullString  `json:"error_message"`
}

func (q *Queries) CreateOrderExecution(ctx context.Context, arg CreateOrderExecutionParams) (OrderExecution, error) {
	row := q.db.QueryRowContext(ctx, createOrderExecution,
		arg.OrderPlanID,
		arg.ExchangeOrderID,
		arg.ClientOrderID,
		arg.Status,
		arg.FilledQuantity,
		arg.AvgPrice,
		arg.FeeUsdt,
		arg.RawResponse,
		arg.ErrorMessage,
	)
	var i OrderExecution
	err := row.Scan(
		&i.ID,
		&i.OrderPlanID,
		&i.ExchangeOrderID,
		&i.ClientOrderID,
		&i.Status,
		&i.FilledQuantity,
		&i.AvgPrice,
		&i.FeeUsdt,
		&i.RawResponse,
		&i.ErrorMessage,
		&i.SubmittedAt,
		&i.FilledAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderPlan = `-- name: CreateOrderPlan :one
INSERT INTO order_plans (
    idempotency_key,
    config_id,
    agent_id,
    exchange_account_id,
    source,
    exchange,
    account_name,
    symbol,
    side,
    position_side,
    order_type,
    quantity,
    price,
    notional_usdt,
    reduce_only,
    reason,
    status
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17
)
ON CONFLICT (idempotency_key) DO UPDATE SET
    updated_at = now()
RETURNING id, idempotency_key, config_id, agent_id, exchange_account_id, source, exchange, account_name, symbol, side, position_side, order_type, quantity, price, notional_usdt, reduce_only, reason, status, planned_at, created_at, updated_at
`

type CreateOrderPlanParams struct {
	IdempotencyKey    string          `json:"idempotency_key"`
	ConfigID          int64           `json:"config_id"`
	AgentID           int64           `json:"agent_id"`
	ExchangeAccountID int64           `json:"exchange_account_id"`
	Source            string          `json:"source"`
	Exchange          string          `json:"exchange"`
	AccountName       string          `json:"account_name"`
	Symbol            string          `json:"symbol"`
	Side              string          `json:"side"`
	PositionSide      string          `json:"position_side"`
	OrderType         string          `json:"order_type"`
	Quantity          decimal.Decimal `json:"quantity"`
	Price             decimal.Decimal `json:"price"`
	NotionalUsdt      decimal.Decimal `json:"notional_usdt"`
	ReduceOnly        bool            `json:"reduce_only"`
	Reason            string          `json:"reason"`
	Status            string          `json:"status"`
}

func (q *Queries) CreateOrderPlan(ctx context.Context, arg CreateOrderPlanParams) (OrderPlan, error) {
	row := q.db.QueryRowContext(ctx, createOrderPlan,
		arg.IdempotencyKey,
		arg.ConfigID,
		arg.AgentID,
		arg.ExchangeAccountID,
		arg.Source,
		arg.Exchange,
		arg.AccountName,
		arg.Symbol,
		arg.Side,
		arg.PositionSide,
		arg.OrderType,
		arg.Quantity,
		arg.Price,
		arg.NotionalUsdt,
		arg.ReduceOnly,
		arg.Reason,
		arg.Status,
	)
	var i OrderPlan
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.ConfigID,
		&i.AgentID,
		&i.ExchangeAccountID,
		&i.Source,
		&i.Exchange,
		&i.AccountName,
		&i.Symbol,
		&i.Side,
		&i.PositionSide,
		&i.OrderType,
		&i.Quantity,
		&i.Price,
		&i.NotionalUsdt,
		&i.ReduceOnly,
		&i.Reason,
		&i.Status,
		&i.PlannedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExposureSnapshot = `-- name: GetExposureSnapshot :one
SELECT id, agent_id, source, symbol, net_quantity, net_notional_usdt, mark_price, observed_at, created_at, updated_at
FROM exposure_snapshots
WHERE agent_id = $1
  AND source = $2
  AND symbol = $3
`

type GetExposureSnapshotParams struct {
	AgentID int64  `json:"agent_id"`
	Source  string `json:"source"`
	Symbol  string `json:"symbol"`
}

func (q *Queries) GetExposureSnapshot(ctx context.Context, arg GetExposureSnapshotParams) (ExposureSnapshot, error) {
	row := q.db.QueryRowContext(ctx, getExposureSnapshot, arg.AgentID, arg.Source, arg.Symbol)
	var i ExposureSnapshot
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Source,
		&i.Symbol,
		&i.NetQuantity,
		&i.NetNotionalUsdt,
		&i.MarkPrice,
		&i.ObservedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHedgePositionSnapshot = `-- name: GetHedgePositionSnapshot :one
SELECT id, agent_id, exchange_account_id, exchange, account_name, symbol, position_side, quantity, notional_usdt, entry_price, mark_price, observed_at, created_at, updated_at
FROM hedge_position_snapshots
WHERE agent_id = $1
  AND exchange_account_id = $2
  AND symbol = $3
`

type GetHedgePositionSnapshotParams struct {
	AgentID           int64  `json:"agent_id"`
	ExchangeAccountID int64  `json:"exchange_account_id"`
	Symbol            string `json:"symbol"`
}

func (q *Queries) GetHedgePositionSnapshot(ctx context.Context, arg GetHedgePositionSnapshotParams) (HedgePositionSnapshot, error) {
	row := q.db.QueryRowContext(ctx, getHedgePositionSnapshot, arg.AgentID, arg.ExchangeAccountID, arg.Symbol)
	var i HedgePositionSnapshot
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.ExchangeAccountID,
		&i.Exchange,
		&i.AccountName,
		&i.Symbol,
		&i.PositionSide,
		&i.Quantity,
		&i.NotionalUsdt,
		&i.EntryPrice,
		&i.MarkPrice,
		&i.ObservedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderExecutionByClientOrderID = `-- name: GetOrderExecutionByClientOrderID :one
SELECT id, order_plan_id, exchange_order_id, client_order_id, status, filled_quantity, avg_price, fee_usdt, raw_response, error_message, submitted_at, filled_at, failed_at, created_at, updated_at
FROM order_executions
WHERE client_order_id = $1
`

func (q *Queries) GetOrderExecutionByClientOrderID(ctx context.Context, clientOrderID string) (OrderExecution, error) {
	row := q.db.QueryRowContext(ctx, getOrderExecutionByClientOrderID, clientOrderID)
	var i OrderExecution
	err := row.Scan(
		&i.ID,
		&i.OrderPlanID,
		&i.ExchangeOrderID,
		&i.ClientOrderID,
		&i.Status,
		&i.FilledQuantity,
		&i.AvgPrice,
		&i.FeeUsdt,
		&i.RawResponse,
		&i.ErrorMessage,
		&i.SubmittedAt,
		&i.FilledAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllExposureSnapshots = `-- name: ListAllExposureSnapshots :many
SELECT id, agent_id, source, symbol, net_quantity, net_notional_usdt, mark_price, observed_at, created_at, updated_at
FROM exposure_snapshots
ORDER BY agent_id ASC, source ASC, symbol ASC
`

func (q *Queries) ListAllExposureSnapshots(ctx context.Context) ([]ExposureSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listAllExposureSnapshots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExposureSnapshot
	for rows.Next() {
		var i ExposureSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Source,
			&i.Symbol,
			&i.NetQuantity,
			&i.NetNotionalUsdt,
			&i.MarkPrice,
			&i.ObservedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllHedgePositionSnapshots = `-- name: ListAllHedgePositionSnapshots :many
SELECT id, agent_id, exchange_account_id, exchange, account_name, symbol, position_side, quantity, notional_usdt, entry_price, mark_price, observed_at, created_at, updated_at
FROM hedge_position_snapshots
ORDER BY agent_id ASC, exchange_account_id ASC, symbol ASC
`

func (q *Queries) ListAllHedgePositionSnapshots(ctx context.Context) ([]HedgePositionSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listAllHedgePositionSnapshots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HedgePositionSnapshot
	for rows.Next() {
		var i HedgePositionSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.ExchangeAccountID,
			&i.Exchange,
			&i.AccountName,
			&i.Symbol,
			&i.PositionSide,
			&i.Quantity,
			&i.NotionalUsdt,
			&i.EntryPrice,
			&i.MarkPrice,
			&i.ObservedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExposureSnapshots = `-- name: ListExposureSnapshots :many
SELECT id, agent_id, source, symbol, net_quantity, net_notional_usdt, mark_price, observed_at, created_at, updated_at
FROM exposure_snapshots
WHERE source = $1
ORDER BY observed_at DESC, symbol ASC
`

func (q *Queries) ListExposureSnapshots(ctx context.Context, source string) ([]ExposureSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listExposureSnapshots, source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExposureSnapshot
	for rows.Next() {
		var i ExposureSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Source,
			&i.Symbol,
			&i.NetQuantity,
			&i.NetNotionalUsdt,
			&i.MarkPrice,
			&i.ObservedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHedgeMonitorSnapshots = `-- name: ListHedgeMonitorSnapshots :many
SELECT id, agent_id, config_id, exchange_account_id, source, symbol, target_symbol, exchange, account_name, net_quantity, net_notional_usdt, target_hedge_usdt, actual_hedge_usdt, adjustment_usdt, switch_status, health_status, action_status, status, status_reason, exposure_observed_at, position_observed_at, calculated_at, created_at, updated_at
FROM hedge_monitor_snapshots
WHERE agent_id = $1
ORDER BY symbol ASC, config_id ASC
`

func (q *Queries) ListHedgeMonitorSnapshots(ctx context.Context, agentID int64) ([]HedgeMonitorSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listHedgeMonitorSnapshots, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HedgeMonitorSnapshot
	for rows.Next() {
		var i HedgeMonitorSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.ConfigID,
			&i.ExchangeAccountID,
			&i.Source,
			&i.Symbol,
			&i.TargetSymbol,
			&i.Exchange,
			&i.AccountName,
			&i.NetQuantity,
			&i.NetNotionalUsdt,
			&i.TargetHedgeUsdt,
			&i.ActualHedgeUsdt,
			&i.AdjustmentUsdt,
			&i.SwitchStatus,
			&i.HealthStatus,
			&i.ActionStatus,
			&i.Status,
			&i.StatusReason,
			&i.ExposureObservedAt,
			&i.PositionObservedAt,
			&i.CalculatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestOrderExecutionStates = `-- name: ListLatestOrderExecutionStates :many
SELECT DISTINCT ON (plan.config_id)
    plan.config_id,
    execution.status,
    COALESCE(execution.error_message, '')::text AS error_message,
    execution.updated_at
FROM order_plans AS plan
JOIN order_executions AS execution ON execution.order_plan_id = plan.id
ORDER BY plan.config_id, execution.updated_at DESC, execution.id DESC
`

type ListLatestOrderExecutionStatesRow struct {
	ConfigID     int64     `json:"config_id"`
	Status       string    `json:"status"`
	ErrorMessage string    `json:"error_message"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) ListLatestOrderExecutionStates(ctx context.Context) ([]ListLatestOrderExecutionStatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listLatestOrderExecutionStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestOrderExecutionStatesRow
	for rows.Next() {
		var i ListLatestOrderExecutionStatesRow
		if err := rows.Scan(
			&i.ConfigID,
			&i.Status,
			&i.ErrorMessage,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentAuditEvents = `-- name: ListRecentAuditEvents :many
SELECT id, event_type, severity, symbol, message, payload, created_at
FROM audit_events
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListRecentAuditEvents(ctx context.Context, limit int32) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listRecentAuditEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Severity,
			&i.Symbol,
			&i.Message,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneHedgeMonitorSnapshots = `-- name: PruneHedgeMonitorSnapshots :execrows
DELETE FROM hedge_monitor_snapshots
WHERE NOT EXISTS (
    SELECT 1
    FROM hedge_configs
    WHERE hedge_configs.id = hedge_monitor_snapshots.config_id
      AND hedge_configs.deleted_at IS NULL
)
`

func (q *Queries) PruneHedgeMonitorSnapshots(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneHedgeMonitorSnapshots)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateOrderExecutionStatus = `-- name: UpdateOrderExecutionStatus :one
UPDATE order_executions
SET
    exchange_order_id = $2,
    status = $3,
    filled_quantity = $4,
    avg_price = $5,
    fee_usdt = $6,
    raw_response = $7,
    error_message = $8,
    submitted_at = CASE
        WHEN $3 IN ('submitted', 'filled') THEN COALESCE(submitted_at, now())
        ELSE submitted_at
    END,
    filled_at = CASE
        WHEN $3 = 'filled' THEN COALESCE(filled_at, now())
        ELSE filled_at
    END,
    failed_at = CASE
        WHEN $3 = 'failed' THEN COALESCE(failed_at, now())
        ELSE failed_at
    END
WHERE id = $1
RETURNING id, order_plan_id, exchange_order_id, client_order_id, status, filled_quantity, avg_price, fee_usdt, raw_response, error_message, submitted_at, filled_at, failed_at, created_at, updated_at
`

type UpdateOrderExecutionStatusParams struct {
	ID              int64           `json:"id"`
	ExchangeOrderID sql.NullString  `json:"exchange_order_id"`
	Status          string          `json:"status"`
	FilledQuantity  decimal.Decimal `json:"filled_quantity"`
	AvgPrice        decimal.Decimal `json:"avg_price"`
	FeeUsdt         decimal.Decimal `json:"fee_usdt"`
	RawResponse     json.RawMessage `json:"raw_response"`
	ErrorMessage    sql.NullString  `json:"error_message"`
}

func (q *Queries) UpdateOrderExecutionStatus(ctx context.Context, arg UpdateOrderExecutionStatusParams) (OrderExecution, error) {
	row := q.db.QueryRowContext(ctx, updateOrderExecutionStatus,
		arg.ID,
		arg.ExchangeOrderID,
		arg.Status,
		arg.FilledQuantity,
		arg.AvgPrice,
		arg.FeeUsdt,
		arg.RawResponse,
		arg.ErrorMessage,
	)
	var i OrderExecution
	err := row.Scan(
		&i.ID,
		&i.OrderPlanID,
		&i.ExchangeOrderID,
		&i.ClientOrderID,
		&i.Status,
		&i.FilledQuantity,
		&i.AvgPrice,
		&i.FeeUsdt,
		&i.RawResponse,
		&i.ErrorMessage,
		&i.SubmittedAt,
		&i.FilledAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderPlanStatus = `-- name: UpdateOrderPlanStatus :one
UPDATE order_plans
SET status = $2
WHERE id = $1
RETURNING id, idempotency_key, config_id, agent_id, exchange_account_id, source, exchange, account_name, symbol, side, position_side, order_type, quantity, price, notional_usdt, reduce_only, reason, status, planned_at, created_at, updated_at
`

type UpdateOrderPlanStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateOrderPlanStatus(ctx context.Context, arg UpdateOrderPlanStatusParams) (OrderPlan, error) {
	row := q.db.QueryRowContext(ctx, updateOrderPlanStatus, arg.ID, arg.Status)
	var i OrderPlan
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.ConfigID,
		&i.AgentID,
		&i.ExchangeAccountID,
		&i.Source,
		&i.Exchange,
		&i.AccountName,
		&i.Symbol,
		&i.Side,
		&i.PositionSide,
		&i.OrderType,
		&i.Quantity,
		&i.Price,
		&i.NotionalUsdt,
		&i.ReduceOnly,
		&i.Reason,
		&i.Status,
		&i.PlannedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertExposureSnapshot = `-- name: UpsertExposureSnapshot :one
INSERT INTO exposure_snapshots (
    agent_id,
    source,
    symbol,
    net_quantity,
    net_notional_usdt,
    mark_price,
    observed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
ON CONFLICT (agent_id, source, symbol) DO UPDATE SET
    net_quantity = EXCLUDED.net_quantity,
    net_notional_usdt = EXCLUDED.net_notional_usdt,
    mark_price = EXCLUDED.mark_price,
    observed_at = EXCLUDED.observed_at
RETURNING id, agent_id, source, symbol, net_quantity, net_notional_usdt, mark_price, observed_at, created_at, updated_at
`

type UpsertExposureSnapshotParams struct {
	AgentID         int64           `json:"agent_id"`
	Source          string          `json:"source"`
	Symbol          string          `json:"symbol"`
	NetQuantity     decimal.Decimal `json:"net_quantity"`
	NetNotionalUsdt decimal.Decimal `json:"net_notional_usdt"`
	MarkPrice       decimal.Decimal `json:"mark_price"`
	ObservedAt      time.Time       `json:"observed_at"`
}

func (q *Queries) UpsertExposureSnapshot(ctx context.Context, arg UpsertExposureSnapshotParams) (ExposureSnapshot, error) {
	row := q.db.QueryRowContext(ctx, upsertExposureSnapshot,
		arg.AgentID,
		arg.Source,
		arg.Symbol,
		arg.NetQuantity,
		arg.NetNotionalUsdt,
		arg.MarkPrice,
		arg.ObservedAt,
	)
	var i ExposureSnapshot
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Source,
		&i.Symbol,
		&i.NetQuantity,
		&i.NetNotionalUsdt,
		&i.MarkPrice,
		&i.ObservedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertHedgeMonitorSnapshot = `-- name: UpsertHedgeMonitorSnapshot :one
INSERT INTO hedge_monitor_snapshots (
    agent_id,
    config_id,
    exchange_account_id,
    source,
    symbol,
    target_symbol,
    exchange,
    account_name,
    net_quantity,
    net_notional_usdt,
    target_hedge_usdt,
    actual_hedge_usdt,
    adjustment_usdt,
    switch_status,
    health_status,
    action_status,
    status,
    status_reason,
    exposure_observed_at,
    position_observed_at,
    calculated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13, $14,
    $15, $16, $17, $18, $19, $20, $21
)
ON CONFLICT (config_id) DO UPDATE SET
    agent_id = EXCLUDED.agent_id,
    exchange_account_id = EXCLUDED.exchange_account_id,
    source = EXCLUDED.source,
    symbol = EXCLUDED.symbol,
    target_symbol = EXCLUDED.target_symbol,
    exchange = EXCLUDED.exchange,
    account_name = EXCLUDED.account_name,
    net_quantity = EXCLUDED.net_quantity,
    net_notional_usdt = EXCLUDED.net_notional_usdt,
    target_hedge_usdt = EXCLUDED.target_hedge_usdt,
    actual_hedge_usdt = EXCLUDED.actual_hedge_usdt,
    adjustment_usdt = EXCLUDED.adjustment_usdt,
    switch_status = EXCLUDED.switch_status,
    health_status = EXCLUDED.health_status,
    action_status = EXCLUDED.action_status,
    status = EXCLUDED.status,
    status_reason = EXCLUDED.status_reason,
    exposure_observed_at = EXCLUDED.exposure_observed_at,
    position_observed_at = EXCLUDED.position_observed_at,
    calculated_at = EXCLUDED.calculated_at
RETURNING id, agent_id, config_id, exchange_account_id, source, symbol, target_symbol, exchange, account_name, net_quantity, net_notional_usdt, target_hedge_usdt, actual_hedge_usdt, adjustment_usdt, switch_status, health_status, action_status, status, status_reason, exposure_observed_at, position_observed_at, calculated_at, created_at, updated_at
`

type UpsertHedgeMonitorSnapshotParams struct {
	AgentID            int64           `json:"agent_id"`
	ConfigID           int64           `json:"config_id"`
	ExchangeAccountID  int64           `json:"exchange_account_id"`
	Source             string          `json:"source"`
	Symbol             string          `json:"symbol"`
	TargetSymbol       string          `json:"target_symbol"`
	Exchange           string          `json:"exchange"`
	AccountName        string          `json:"account_name"`
	NetQuantity        decimal.Decimal `json:"net_quantity"`
	NetNotionalUsdt    decimal.Decimal `json:"net_notional_usdt"`
	TargetHedgeUsdt    decimal.Decimal `json:"target_hedge_usdt"`
	ActualHedgeUsdt    decimal.Decimal `json:"actual_hedge_usdt"`
	AdjustmentUsdt     decimal.Decimal `json:"adjustment_usdt"`
	SwitchStatus       string          `json:"switch_status"`
	HealthStatus       string          `json:"health_status"`
	ActionStatus       string          `json:"action_status"`
	Status             string          `json:"status"`
	StatusReason       string          `json:"status_reason"`
	ExposureObservedAt sql.NullTime    `json:"exposure_observed_at"`
	PositionObservedAt sql.NullTime    `json:"position_observed_at"`
	CalculatedAt       time.Time       `json:"calculated_at"`
}

func (q *Queries) UpsertHedgeMonitorSnapshot(ctx context.Context, arg UpsertHedgeMonitorSnapshotParams) (HedgeMonitorSnapshot, error) {
	row := q.db.QueryRowContext(ctx, upsertHedgeMonitorSnapshot,
		arg.AgentID,
		arg.ConfigID,
		arg.ExchangeAccountID,
		arg.Source,
		arg.Symbol,
		arg.TargetSymbol,
		arg.Exchange,
		arg.AccountName,
		arg.NetQuantity,
		arg.NetNotionalUsdt,
		arg.TargetHedgeUsdt,
		arg.ActualHedgeUsdt,
		arg.AdjustmentUsdt,
		arg.SwitchStatus,
		arg.HealthStatus,
		arg.ActionStatus,
		arg.Status,
		arg.StatusReason,
		arg.ExposureObservedAt,
		arg.PositionObservedAt,
		arg.CalculatedAt,
	)
	var i HedgeMonitorSnapshot
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.ConfigID,
		&i.ExchangeAccountID,
		&i.Source,
		&i.Symbol,
		&i.TargetSymbol,
		&i.Exchange,
		&i.AccountName,
		&i.NetQuantity,
		&i.NetNotionalUsdt,
		&i.TargetHedgeUsdt,
		&i.ActualHedgeUsdt,
		&i.AdjustmentUsdt,
		&i.SwitchStatus,
		&i.HealthStatus,
		&i.ActionStatus,
		&i.Status,
		&i.StatusReason,
		&i.ExposureObservedAt,
		&i.PositionObservedAt,
		&i.CalculatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertHedgePositionSnapshot = `-- name: UpsertHedgePositionSnapshot :one
INSERT INTO hedge_position_snapshots (
    agent_id,
    exchange_account_id,
    exchange,
    account_name,
    symbol,
    position_side,
    quantity,
    notional_usdt,
    entry_price,
    mark_price,
    observed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
ON CONFLICT (agent_id, exchange_account_id, symbol) DO UPDATE SET
    exchange = EXCLUDED.exchange,
    account_name = EXCLUDED.account_name,
    position_side = EXCLUDED.position_side,
    quantity = EXCLUDED.quantity,
    notional_usdt = EXCLUDED.notional_usdt,
    entry_price = EXCLUDED.entry_price,
    mark_price = EXCLUDED.mark_price,
    observed_at = EXCLUDED.observed_at
RETURNING id, agent_id, exchange_account_id, exchange, account_name, symbol, position_side, quantity, notional_usdt, entry_price, mark_price, observed_at, created_at, updated_at
`

type UpsertHedgePositionSnapshotParams struct {
	AgentID           int64           `json:"agent_id"`
	ExchangeAccountID int64           `json:"exchange_account_id"`
	Exchange          string          `json:"exchange"`
	AccountName       string          `json:"account_name"`
	Symbol            string          `json:"symbol"`
	PositionSide      string          `json:"position_side"`
	Quantity          decimal.Decimal `json:"quantity"`
	NotionalUsdt      decimal.Decimal `json:"notional_usdt"`
	EntryPrice        decimal.Decimal `json:"entry_price"`
	MarkPrice         decimal.Decimal `json:"mark_price"`
	ObservedAt        time.Time       `json:"observed_at"`
}

func (q *Queries) UpsertHedgePositionSnapshot(ctx context.Context, arg UpsertHedgePositionSnapshotParams) (HedgePositionSnapshot, error) {
	row := q.db.QueryRowContext(ctx, upsertHedgePositionSnapshot,
		arg.AgentID,
		arg.ExchangeAccountID,
		arg.Exchange,
		arg.AccountName,
		arg.Symbol,
		arg.PositionSide,
		arg.Quantity,
		arg.NotionalUsdt,
		arg.EntryPrice,
		arg.MarkPrice,
		arg.ObservedAt,
	)
	var i HedgePositionSnapshot
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.ExchangeAccountID,
		&i.Exchange,
		&i.AccountName,
		&i.Symbol,
		&i.PositionSide,
		&i.Quantity,
		&i.NotionalUsdt,
		&i.EntryPrice,
		&i.MarkPrice,
		&i.ObservedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
