// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package coredb

import (
	"database/sql"
	"encoding/json"
	"time"

	decimal "github.com/shopspring/decimal"
)

type AuditEvent struct {
	ID        int64           `json:"id"`
	EventType string          `json:"event_type"`
	Severity  string          `json:"severity"`
	Symbol    string          `json:"symbol"`
	Message   string          `json:"message"`
	Payload   json.RawMessage `json:"payload"`
	CreatedAt time.Time       `json:"created_at"`
}

type ExchangeAccount struct {
	ID                  int64           `json:"id"`
	Exchange            string          `json:"exchange"`
	Name                string          `json:"name"`
	CcxtID              string          `json:"ccxt_id"`
	MarketType          string          `json:"market_type"`
	Sandbox             bool            `json:"sandbox"`
	DefaultSettle       string          `json:"default_settle"`
	AccountType         string          `json:"account_type"`
	ProductType         string          `json:"product_type"`
	Category            string          `json:"category"`
	PositionMode        string          `json:"position_mode"`
	MarginMode          string          `json:"margin_mode"`
	RecvWindowMs        int32           `json:"recv_window_ms"`
	RateLimitMs         int32           `json:"rate_limit_ms"`
	AllowedSymbols      json.RawMessage `json:"allowed_symbols"`
	ApiKeyEncrypted     string          `json:"api_key_encrypted"`
	ApiKeyHint          string          `json:"api_key_hint"`
	ApiSecretEncrypted  string          `json:"api_secret_encrypted"`
	PassphraseEncrypted string          `json:"passphrase_encrypted"`
	Status              string          `json:"status"`
	IsPrimary           bool            `json:"is_primary"`
	Metadata            json.RawMessage `json:"metadata"`
	CreatedAt           time.Time       `json:"created_at"`
	UpdatedAt           time.Time       `json:"updated_at"`
	DeletedAt           sql.NullTime    `json:"deleted_at"`
}

type ExposureSnapshot struct {
	ID              int64           `json:"id"`
	AgentID         int64           `json:"agent_id"`
	Source          string          `json:"source"`
	Symbol          string          `json:"symbol"`
	NetQuantity     decimal.Decimal `json:"net_quantity"`
	NetNotionalUsdt decimal.Decimal `json:"net_notional_usdt"`
	MarkPrice       decimal.Decimal `json:"mark_price"`
	ObservedAt      time.Time       `json:"observed_at"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}

type HedgeConfig struct {
	ID                int64           `json:"id"`
	ExchangeAccountID int64           `json:"exchange_account_id"`
	Source            string          `json:"source"`
	Symbol            string          `json:"symbol"`
	TargetSymbol      string          `json:"target_symbol"`
	TargetHedgeRatio  decimal.Decimal `json:"target_hedge_ratio"`
	FirstTriggerUsdt  decimal.Decimal `json:"first_trigger_usdt"`
	RebalanceUsdt     decimal.Decimal `json:"rebalance_usdt"`
	ExitUsdt          decimal.Decimal `json:"exit_usdt"`
	MaxSlippageBps    int32           `json:"max_slippage_bps"`
	MaxNotionalUsdt   decimal.Decimal `json:"max_notional_usdt"`
	MinOrderUsdt      decimal.Decimal `json:"min_order_usdt"`
	Leverage          int32           `json:"leverage"`
	Enabled           bool            `json:"enabled"`
	DryRun            bool            `json:"dry_run"`
	Metadata          json.RawMessage `json:"metadata"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
	DeletedAt         sql.NullTime    `json:"deleted_at"`
}

type HedgeMonitorSnapshot struct {
	ID                 int64           `json:"id"`
	AgentID            int64           `json:"agent_id"`
	ConfigID           int64           `json:"config_id"`
	ExchangeAccountID  int64           `json:"exchange_account_id"`
	Source             string          `json:"source"`
	Symbol             string          `json:"symbol"`
	TargetSymbol       string          `json:"target_symbol"`
	Exchange           string          `json:"exchange"`
	AccountName        string          `json:"account_name"`
	NetQuantity        decimal.Decimal `json:"net_quantity"`
	NetNotionalUsdt    decimal.Decimal `json:"net_notional_usdt"`
	TargetHedgeUsdt    decimal.Decimal `json:"target_hedge_usdt"`
	ActualHedgeUsdt    decimal.Decimal `json:"actual_hedge_usdt"`
	AdjustmentUsdt     decimal.Decimal `json:"adjustment_usdt"`
	SwitchStatus       string          `json:"switch_status"`
	HealthStatus       string          `json:"health_status"`
	ActionStatus       string          `json:"action_status"`
	Status             string          `json:"status"`
	StatusReason       string          `json:"status_reason"`
	ExposureObservedAt sql.NullTime    `json:"exposure_observed_at"`
	PositionObservedAt sql.NullTime    `json:"position_observed_at"`
	CalculatedAt       time.Time       `json:"calculated_at"`
	CreatedAt          time.Time       `json:"created_at"`
	UpdatedAt          time.Time       `json:"updated_at"`
}

type HedgePositionSnapshot struct {
	ID                int64           `json:"id"`
	AgentID           int64           `json:"agent_id"`
	ExchangeAccountID int64           `json:"exchange_account_id"`
	Exchange          string          `json:"exchange"`
	AccountName       string          `json:"account_name"`
	Symbol            string          `json:"symbol"`
	PositionSide      string          `json:"position_side"`
	Quantity          decimal.Decimal `json:"quantity"`
	NotionalUsdt      decimal.Decimal `json:"notional_usdt"`
	EntryPrice        decimal.Decimal `json:"entry_price"`
	MarkPrice         decimal.Decimal `json:"mark_price"`
	ObservedAt        time.Time       `json:"observed_at"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
}

type OrderExecution struct {
	ID              int64           `json:"id"`
	OrderPlanID     int64           `json:"order_plan_id"`
	ExchangeOrderID sql.NullString  `json:"exchange_order_id"`
	ClientOrderID   string          `json:"client_order_id"`
	Status          string          `json:"status"`
	FilledQuantity  decimal.Decimal `json:"filled_quantity"`
	AvgPrice        decimal.Decimal `json:"avg_price"`
	FeeUsdt         decimal.Decimal `json:"fee_usdt"`
	RawResponse     json.RawMessage `json:"raw_response"`
	ErrorMessage    sql.NullString  `json:"error_message"`
	SubmittedAt     sql.NullTime    `json:"submitted_at"`
	FilledAt        sql.NullTime    `json:"filled_at"`
	FailedAt        sql.NullTime    `json:"failed_at"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}

type OrderPlan struct {
	ID                int64           `json:"id"`
	IdempotencyKey    string          `json:"idempotency_key"`
	ConfigID          int64           `json:"config_id"`
	AgentID           int64           `json:"agent_id"`
	ExchangeAccountID int64           `json:"exchange_account_id"`
	Source            string          `json:"source"`
	Exchange          string          `json:"exchange"`
	AccountName       string          `json:"account_name"`
	Symbol            string          `json:"symbol"`
	Side              string          `json:"side"`
	PositionSide      string          `json:"position_side"`
	OrderType         string          `json:"order_type"`
	Quantity          decimal.Decimal `json:"quantity"`
	Price             decimal.Decimal `json:"price"`
	NotionalUsdt      decimal.Decimal `json:"notional_usdt"`
	ReduceOnly        bool            `json:"reduce_only"`
	Reason            string          `json:"reason"`
	Status            string          `json:"status"`
	PlannedAt         time.Time       `json:"planned_at"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
}

type SchemaMigration struct {
	Version   int64     `json:"version"`
	Name      string    `json:"name"`
	AppliedAt time.Time `json:"applied_at"`
}
