// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package coredb

import (
	"context"
)

type Querier interface {
	CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvent, error)
	CreateOrderExecution(ctx context.Context, arg CreateOrderExecutionParams) (OrderExecution, error)
	CreateOrderPlan(ctx context.Context, arg CreateOrderPlanParams) (OrderPlan, error)
	GetExposureSnapshot(ctx context.Context, arg GetExposureSnapshotParams) (ExposureSnapshot, error)
	GetHedgePositionSnapshot(ctx context.Context, arg GetHedgePositionSnapshotParams) (HedgePositionSnapshot, error)
	GetOrderExecutionByClientOrderID(ctx context.Context, clientOrderID string) (OrderExecution, error)
	ListAllExposureSnapshots(ctx context.Context) ([]ExposureSnapshot, error)
	ListAllHedgePositionSnapshots(ctx context.Context) ([]HedgePositionSnapshot, error)
	ListExposureSnapshots(ctx context.Context, source string) ([]ExposureSnapshot, error)
	ListHedgeMonitorSnapshots(ctx context.Context, agentID int64) ([]HedgeMonitorSnapshot, error)
	ListLatestOrderExecutionStates(ctx context.Context) ([]ListLatestOrderExecutionStatesRow, error)
	ListRecentAuditEvents(ctx context.Context, limit int32) ([]AuditEvent, error)
	PruneHedgeMonitorSnapshots(ctx context.Context) (int64, error)
	UpdateOrderExecutionStatus(ctx context.Context, arg UpdateOrderExecutionStatusParams) (OrderExecution, error)
	UpdateOrderPlanStatus(ctx context.Context, arg UpdateOrderPlanStatusParams) (OrderPlan, error)
	UpsertExposureSnapshot(ctx context.Context, arg UpsertExposureSnapshotParams) (ExposureSnapshot, error)
	UpsertHedgeMonitorSnapshot(ctx context.Context, arg UpsertHedgeMonitorSnapshotParams) (HedgeMonitorSnapshot, error)
	UpsertHedgePositionSnapshot(ctx context.Context, arg UpsertHedgePositionSnapshotParams) (HedgePositionSnapshot, error)
}

var _ Querier = (*Queries)(nil)
