-- 将已经执行过旧版英文注释的数据库注释更新为中文。

COMMENT ON TABLE schema_migrations IS '记录服务已经执行过的数据库迁移。';
COMMENT ON COLUMN schema_migrations.version IS '从迁移文件名解析出来的迁移版本号。';
COMMENT ON COLUMN schema_migrations.name IS '从迁移文件名解析出来的迁移名称。';
COMMENT ON COLUMN schema_migrations.applied_at IS '迁移被记录为已执行的时间。';

COMMENT ON TABLE exchange_accounts IS '交易所账户配置表，保存交易所连接信息、市场类型、风控限制和加密后的凭证信息。';
COMMENT ON COLUMN exchange_accounts.id IS '交易所账户主键。';
COMMENT ON COLUMN exchange_accounts.exchange IS '交易所展示名称，例如 Binance、Bybit、OKX、Gate、Hyperliquid 或 Aster。';
COMMENT ON COLUMN exchange_accounts.name IS '本地账户名称，用于区分同一交易所下的不同账户。';
COMMENT ON COLUMN exchange_accounts.ccxt_id IS 'CCXT 交易所标识，例如 binanceusdm、bybit、bitget、okx、gate、hyperliquid 或 aster。';
COMMENT ON COLUMN exchange_accounts.market_type IS '账户使用的市场类型：spot 现货、margin 杠杆、swap 永续合约、future 交割合约。';
COMMENT ON COLUMN exchange_accounts.sandbox IS '是否使用沙盒、测试网或模拟盘环境。';
COMMENT ON COLUMN exchange_accounts.default_settle IS '合约交易默认结算币种，例如 USDT、USDC、BTC 或 ETH。';
COMMENT ON COLUMN exchange_accounts.account_type IS '交易所接口需要的账户类型。';
COMMENT ON COLUMN exchange_accounts.product_type IS '交易所接口需要的产品类型，例如 USDT-FUTURES 或 COIN-FUTURES。';
COMMENT ON COLUMN exchange_accounts.category IS '交易所接口需要的产品分类，例如 linear 或 inverse。';
COMMENT ON COLUMN exchange_accounts.position_mode IS '下单使用的持仓模式：one_way 单向持仓，hedge 双向持仓。';
COMMENT ON COLUMN exchange_accounts.margin_mode IS '合约交易使用的保证金模式：cross 全仓，isolated 逐仓。';
COMMENT ON COLUMN exchange_accounts.recv_window_ms IS '交易所请求允许的时间窗口，单位毫秒。';
COMMENT ON COLUMN exchange_accounts.rate_limit_ms IS '请求最小间隔或交易所限频提示，单位毫秒。';
COMMENT ON COLUMN exchange_accounts.allowed_symbols IS '允许该账户交易的交易对 JSON 数组。';
COMMENT ON COLUMN exchange_accounts.api_key_encrypted IS '加密后的 API Key。';
COMMENT ON COLUMN exchange_accounts.api_key_hint IS '脱敏后的 API Key 提示，用于页面展示和排查。';
COMMENT ON COLUMN exchange_accounts.api_secret_encrypted IS '加密后的 API Secret。';
COMMENT ON COLUMN exchange_accounts.passphrase_encrypted IS '加密后的交易所 API Passphrase，部分交易所需要。';
COMMENT ON COLUMN exchange_accounts.status IS '账户状态：active 启用，disabled 禁用。';
COMMENT ON COLUMN exchange_accounts.is_primary IS '是否为主要执行账户。';
COMMENT ON COLUMN exchange_accounts.metadata IS '额外的交易所配置，使用 JSON 保存。';
COMMENT ON COLUMN exchange_accounts.created_at IS '交易所账户创建时间。';
COMMENT ON COLUMN exchange_accounts.updated_at IS '交易所账户最后更新时间。';
COMMENT ON COLUMN exchange_accounts.deleted_at IS '软删除时间，为空表示正常查询中可用。';

COMMENT ON TABLE hedge_configs IS '对冲配置表，保存每个交易对的对冲策略参数和风险阈值。';
COMMENT ON COLUMN hedge_configs.id IS '对冲配置主键。';
COMMENT ON COLUMN hedge_configs.exchange_account_id IS '执行该对冲配置订单的交易所账户 ID。';
COMMENT ON COLUMN hedge_configs.source IS '上游风险敞口来源，例如 platform。';
COMMENT ON COLUMN hedge_configs.symbol IS '需要被对冲的上游交易对。';
COMMENT ON COLUMN hedge_configs.target_symbol IS '实际用于下对冲单的交易所交易对。';
COMMENT ON COLUMN hedge_configs.target_hedge_ratio IS '目标对冲比例。';
COMMENT ON COLUMN hedge_configs.first_trigger_usdt IS '首次触发对冲的 USDT 敞口阈值。';
COMMENT ON COLUMN hedge_configs.rebalance_usdt IS '触发再平衡的 USDT 名义价值偏差阈值。';
COMMENT ON COLUMN hedge_configs.exit_usdt IS '低于该 USDT 名义价值时可减少或退出对冲。';
COMMENT ON COLUMN hedge_configs.max_slippage_bps IS '允许的最大滑点，单位为基点。';
COMMENT ON COLUMN hedge_configs.max_notional_usdt IS '该配置允许的最大对冲名义价值，0 表示不额外限制。';
COMMENT ON COLUMN hedge_configs.min_order_usdt IS '最小下单名义价值，单位 USDT。';
COMMENT ON COLUMN hedge_configs.leverage IS '规划对冲订单时使用的杠杆倍数。';
COMMENT ON COLUMN hedge_configs.enabled IS '该对冲配置是否启用。';
COMMENT ON COLUMN hedge_configs.dry_run IS '是否只模拟下单，不向交易所真实提交订单。';
COMMENT ON COLUMN hedge_configs.metadata IS '额外的策略或交易所配置，使用 JSON 保存。';
COMMENT ON COLUMN hedge_configs.created_at IS '对冲配置创建时间。';
COMMENT ON COLUMN hedge_configs.updated_at IS '对冲配置最后更新时间。';
COMMENT ON COLUMN hedge_configs.deleted_at IS '软删除时间，为空表示正常查询中可用。';

COMMENT ON TABLE exposure_snapshots IS '上游风险敞口快照表，保存对冲计算所需的最新敞口数据。';
COMMENT ON COLUMN exposure_snapshots.id IS '风险敞口快照主键。';
COMMENT ON COLUMN exposure_snapshots.source IS '上游风险敞口来源，例如 platform。';
COMMENT ON COLUMN exposure_snapshots.symbol IS '风险敞口对应的上游交易对。';
COMMENT ON COLUMN exposure_snapshots.net_quantity IS '需要对冲的上游净持仓数量。';
COMMENT ON COLUMN exposure_snapshots.net_notional_usdt IS '换算为 USDT 的上游净敞口名义价值。';
COMMENT ON COLUMN exposure_snapshots.mark_price IS '用于计算上游敞口价值的标记价格。';
COMMENT ON COLUMN exposure_snapshots.observed_at IS '采集到该风险敞口数据的时间。';
COMMENT ON COLUMN exposure_snapshots.created_at IS '风险敞口快照记录创建时间。';
COMMENT ON COLUMN exposure_snapshots.updated_at IS '风险敞口快照记录最后更新时间。';

COMMENT ON TABLE hedge_position_snapshots IS '交易所对冲仓位快照表，用于比较目标对冲敞口和实际持仓敞口。';
COMMENT ON COLUMN hedge_position_snapshots.id IS '对冲仓位快照主键。';
COMMENT ON COLUMN hedge_position_snapshots.exchange IS '对冲账户所属交易所名称。';
COMMENT ON COLUMN hedge_position_snapshots.account_name IS '对冲仓位所属的本地交易所账户名称。';
COMMENT ON COLUMN hedge_position_snapshots.symbol IS '对冲仓位对应的交易所交易对。';
COMMENT ON COLUMN hedge_position_snapshots.position_side IS '交易所返回的持仓方向：NET 净持仓、LONG 多仓、SHORT 空仓。';
COMMENT ON COLUMN hedge_position_snapshots.quantity IS '交易所返回的持仓数量。';
COMMENT ON COLUMN hedge_position_snapshots.notional_usdt IS '换算为 USDT 的仓位名义价值。';
COMMENT ON COLUMN hedge_position_snapshots.entry_price IS '交易所返回的平均开仓价格。';
COMMENT ON COLUMN hedge_position_snapshots.mark_price IS '用于计算对冲仓位价值的标记价格。';
COMMENT ON COLUMN hedge_position_snapshots.observed_at IS '采集到该对冲仓位数据的时间。';
COMMENT ON COLUMN hedge_position_snapshots.created_at IS '对冲仓位快照记录创建时间。';
COMMENT ON COLUMN hedge_position_snapshots.updated_at IS '对冲仓位快照记录最后更新时间。';

COMMENT ON TABLE order_plans IS '对冲订单计划表，保存真实执行前或执行中的幂等下单计划。';
COMMENT ON COLUMN order_plans.id IS '订单计划主键。';
COMMENT ON COLUMN order_plans.idempotency_key IS '幂等键，用于避免同一次对冲动作重复规划或重复提交。';
COMMENT ON COLUMN order_plans.config_id IS '生成该订单计划的对冲配置 ID。';
COMMENT ON COLUMN order_plans.source IS '触发该订单计划的上游风险敞口来源。';
COMMENT ON COLUMN order_plans.exchange IS '计划提交对冲订单的交易所。';
COMMENT ON COLUMN order_plans.account_name IS '执行订单使用的本地账户名称。';
COMMENT ON COLUMN order_plans.symbol IS '计划交易的交易所交易对。';
COMMENT ON COLUMN order_plans.side IS '订单方向：BUY 买入，SELL 卖出。';
COMMENT ON COLUMN order_plans.position_side IS '订单持仓方向：NET 净持仓、LONG 多仓、SHORT 空仓。';
COMMENT ON COLUMN order_plans.order_type IS '订单类型：LIMIT 限价单，MARKET 市价单。';
COMMENT ON COLUMN order_plans.quantity IS '计划下单数量。';
COMMENT ON COLUMN order_plans.price IS '计划下单价格。';
COMMENT ON COLUMN order_plans.notional_usdt IS '换算为 USDT 的计划订单名义价值。';
COMMENT ON COLUMN order_plans.reduce_only IS '该订单是否只允许减少已有仓位。';
COMMENT ON COLUMN order_plans.reason IS '对冲执行类型：first_trigger 首次触发、rebalance 再平衡、exit_hedge 退出对冲、manual_close 手动平仓、hedge_ratio_adjustment 对冲比例调整。';
COMMENT ON COLUMN order_plans.status IS '订单计划状态：planned 已计划、skipped 已跳过、submitted 已提交、filled 已成交、failed 失败、dry_run 模拟执行。';
COMMENT ON COLUMN order_plans.created_at IS '订单计划创建时间。';
COMMENT ON COLUMN order_plans.updated_at IS '订单计划最后更新时间。';

COMMENT ON TABLE order_executions IS '对冲订单执行表，保存已提交订单的执行结果和交易所响应。';
COMMENT ON COLUMN order_executions.id IS '订单执行记录主键。';
COMMENT ON COLUMN order_executions.order_plan_id IS '该执行记录关联的订单计划 ID。';
COMMENT ON COLUMN order_executions.exchange_order_id IS '交易所返回的订单 ID。';
COMMENT ON COLUMN order_executions.client_order_id IS '客户端生成的订单 ID，用于幂等和对账。';
COMMENT ON COLUMN order_executions.status IS '订单执行状态：submitted 已提交、filled 已成交、failed 失败、dry_run 模拟执行。';
COMMENT ON COLUMN order_executions.filled_quantity IS '交易所返回的成交数量。';
COMMENT ON COLUMN order_executions.avg_price IS '交易所返回的平均成交价格。';
COMMENT ON COLUMN order_executions.fee_usdt IS '换算为 USDT 的交易手续费。';
COMMENT ON COLUMN order_executions.raw_response IS '交易所原始响应或模拟响应，使用 JSON 保存。';
COMMENT ON COLUMN order_executions.error_message IS '订单提交或成交处理失败时的错误信息。';
COMMENT ON COLUMN order_executions.created_at IS '订单执行记录创建时间。';
COMMENT ON COLUMN order_executions.updated_at IS '订单执行记录最后更新时间。';

COMMENT ON TABLE audit_events IS '审计事件表，保存对冲机器人产生的操作事件、告警和错误。';
COMMENT ON COLUMN audit_events.id IS '审计事件主键。';
COMMENT ON COLUMN audit_events.event_type IS '机器可读的事件类型。';
COMMENT ON COLUMN audit_events.severity IS '事件级别：info 信息、warn 警告、error 错误。';
COMMENT ON COLUMN audit_events.symbol IS '事件关联的交易对，非交易对事件可为空。';
COMMENT ON COLUMN audit_events.message IS '人工可读的事件消息。';
COMMENT ON COLUMN audit_events.payload IS '结构化事件详情，使用 JSON 保存。';
COMMENT ON COLUMN audit_events.created_at IS '审计事件创建时间。';
