// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.0
// source: hedging/v1/hedging.proto

package hedgingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HedgingService_UpsertExposure_FullMethodName  = "/hedging.v1.HedgingService/UpsertExposure"
	HedgingService_UpsertPosition_FullMethodName  = "/hedging.v1.HedgingService/UpsertPosition"
	HedgingService_RunHedge_FullMethodName        = "/hedging.v1.HedgingService/RunHedge"
	HedgingService_ExitHedge_FullMethodName       = "/hedging.v1.HedgingService/ExitHedge"
	HedgingService_EnqueueHedgeRun_FullMethodName = "/hedging.v1.HedgingService/EnqueueHedgeRun"
)

// HedgingServiceClient is the client API for HedgingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HedgingServiceClient interface {
	UpsertExposure(ctx context.Context, in *UpsertExposureRequest, opts ...grpc.CallOption) (*ExposureSnapshot, error)
	UpsertPosition(ctx context.Context, in *UpsertPositionRequest, opts ...grpc.CallOption) (*PositionSnapshot, error)
	RunHedge(ctx context.Context, in *RunHedgeRequest, opts ...grpc.CallOption) (*RunHedgeResponse, error)
	ExitHedge(ctx context.Context, in *RunHedgeRequest, opts ...grpc.CallOption) (*RunHedgeResponse, error)
	EnqueueHedgeRun(ctx context.Context, in *RunHedgeRequest, opts ...grpc.CallOption) (*EnqueueHedgeRunResponse, error)
}

type hedgingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHedgingServiceClient(cc grpc.ClientConnInterface) HedgingServiceClient {
	return &hedgingServiceClient{cc}
}

func (c *hedgingServiceClient) UpsertExposure(ctx context.Context, in *UpsertExposureRequest, opts ...grpc.CallOption) (*ExposureSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExposureSnapshot)
	err := c.cc.Invoke(ctx, HedgingService_UpsertExposure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hedgingServiceClient) UpsertPosition(ctx context.Context, in *UpsertPositionRequest, opts ...grpc.CallOption) (*PositionSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PositionSnapshot)
	err := c.cc.Invoke(ctx, HedgingService_UpsertPosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hedgingServiceClient) RunHedge(ctx context.Context, in *RunHedgeRequest, opts ...grpc.CallOption) (*RunHedgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunHedgeResponse)
	err := c.cc.Invoke(ctx, HedgingService_RunHedge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hedgingServiceClient) ExitHedge(ctx context.Context, in *RunHedgeRequest, opts ...grpc.CallOption) (*RunHedgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunHedgeResponse)
	err := c.cc.Invoke(ctx, HedgingService_ExitHedge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hedgingServiceClient) EnqueueHedgeRun(ctx context.Context, in *RunHedgeRequest, opts ...grpc.CallOption) (*EnqueueHedgeRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnqueueHedgeRunResponse)
	err := c.cc.Invoke(ctx, HedgingService_EnqueueHedgeRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HedgingServiceServer is the server API for HedgingService service.
// All implementations must embed UnimplementedHedgingServiceServer
// for forward compatibility.
type HedgingServiceServer interface {
	UpsertExposure(context.Context, *UpsertExposureRequest) (*ExposureSnapshot, error)
	UpsertPosition(context.Context, *UpsertPositionRequest) (*PositionSnapshot, error)
	RunHedge(context.Context, *RunHedgeRequest) (*RunHedgeResponse, error)
	ExitHedge(context.Context, *RunHedgeRequest) (*RunHedgeResponse, error)
	EnqueueHedgeRun(context.Context, *RunHedgeRequest) (*EnqueueHedgeRunResponse, error)
	mustEmbedUnimplementedHedgingServiceServer()
}

// UnimplementedHedgingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHedgingServiceServer struct{}

func (UnimplementedHedgingServiceServer) UpsertExposure(context.Context, *UpsertExposureRequest) (*ExposureSnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertExposure not implemented")
}
func (UnimplementedHedgingServiceServer) UpsertPosition(context.Context, *UpsertPositionRequest) (*PositionSnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertPosition not implemented")
}
func (UnimplementedHedgingServiceServer) RunHedge(context.Context, *RunHedgeRequest) (*RunHedgeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunHedge not implemented")
}
func (UnimplementedHedgingServiceServer) ExitHedge(context.Context, *RunHedgeRequest) (*RunHedgeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExitHedge not implemented")
}
func (UnimplementedHedgingServiceServer) EnqueueHedgeRun(context.Context, *RunHedgeRequest) (*EnqueueHedgeRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnqueueHedgeRun not implemented")
}
func (UnimplementedHedgingServiceServer) mustEmbedUnimplementedHedgingServiceServer() {}
func (UnimplementedHedgingServiceServer) testEmbeddedByValue()                        {}

// UnsafeHedgingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HedgingServiceServer will
// result in compilation errors.
type UnsafeHedgingServiceServer interface {
	mustEmbedUnimplementedHedgingServiceServer()
}

func RegisterHedgingServiceServer(s grpc.ServiceRegistrar, srv HedgingServiceServer) {
	// If the following call panics, it indicates UnimplementedHedgingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HedgingService_ServiceDesc, srv)
}

func _HedgingService_UpsertExposure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertExposureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HedgingServiceServer).UpsertExposure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HedgingService_UpsertExposure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HedgingServiceServer).UpsertExposure(ctx, req.(*UpsertExposureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HedgingService_UpsertPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertPositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HedgingServiceServer).UpsertPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HedgingService_UpsertPosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HedgingServiceServer).UpsertPosition(ctx, req.(*UpsertPositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HedgingService_RunHedge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunHedgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HedgingServiceServer).RunHedge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HedgingService_RunHedge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HedgingServiceServer).RunHedge(ctx, req.(*RunHedgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HedgingService_ExitHedge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunHedgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HedgingServiceServer).ExitHedge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HedgingService_ExitHedge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HedgingServiceServer).ExitHedge(ctx, req.(*RunHedgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HedgingService_EnqueueHedgeRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunHedgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HedgingServiceServer).EnqueueHedgeRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HedgingService_EnqueueHedgeRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HedgingServiceServer).EnqueueHedgeRun(ctx, req.(*RunHedgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HedgingService_ServiceDesc is the grpc.ServiceDesc for HedgingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HedgingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hedging.v1.HedgingService",
	HandlerType: (*HedgingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertExposure",
			Handler:    _HedgingService_UpsertExposure_Handler,
		},
		{
			MethodName: "UpsertPosition",
			Handler:    _HedgingService_UpsertPosition_Handler,
		},
		{
			MethodName: "RunHedge",
			Handler:    _HedgingService_RunHedge_Handler,
		},
		{
			MethodName: "ExitHedge",
			Handler:    _HedgingService_ExitHedge_Handler,
		},
		{
			MethodName: "EnqueueHedgeRun",
			Handler:    _HedgingService_EnqueueHedgeRun_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hedging/v1/hedging.proto",
}
