// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.0
// source: hedging/v1/hedging.proto

package hedgingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpsertExposureRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Source          string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Symbol          string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	NetQuantity     string                 `protobuf:"bytes,3,opt,name=net_quantity,json=netQuantity,proto3" json:"net_quantity,omitempty"`
	NetNotionalUsdt string                 `protobuf:"bytes,4,opt,name=net_notional_usdt,json=netNotionalUsdt,proto3" json:"net_notional_usdt,omitempty"`
	MarkPrice       string                 `protobuf:"bytes,5,opt,name=mark_price,json=markPrice,proto3" json:"mark_price,omitempty"`
	ObservedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	AgentId         uint64                 `protobuf:"varint,7,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpsertExposureRequest) Reset() {
	*x = UpsertExposureRequest{}
	mi := &file_hedging_v1_hedging_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertExposureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertExposureRequest) ProtoMessage() {}

func (x *UpsertExposureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hedging_v1_hedging_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertExposureRequest.ProtoReflect.Descriptor instead.
func (*UpsertExposureRequest) Descriptor() ([]byte, []int) {
	return file_hedging_v1_hedging_proto_rawDescGZIP(), []int{0}
}

func (x *UpsertExposureRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *UpsertExposureRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *UpsertExposureRequest) GetNetQuantity() string {
	if x != nil {
		return x.NetQuantity
	}
	return ""
}

func (x *UpsertExposureRequest) GetNetNotionalUsdt() string {
	if x != nil {
		return x.NetNotionalUsdt
	}
	return ""
}

func (x *UpsertExposureRequest) GetMarkPrice() string {
	if x != nil {
		return x.MarkPrice
	}
	return ""
}

func (x *UpsertExposureRequest) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *UpsertExposureRequest) GetAgentId() uint64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

type UpsertPositionRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Exchange          string                 `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	AccountName       string                 `protobuf:"bytes,2,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	Symbol            string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	PositionSide      string                 `protobuf:"bytes,4,opt,name=position_side,json=positionSide,proto3" json:"position_side,omitempty"`
	Quantity          string                 `protobuf:"bytes,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	NotionalUsdt      string                 `protobuf:"bytes,6,opt,name=notional_usdt,json=notionalUsdt,proto3" json:"notional_usdt,omitempty"`
	EntryPrice        string                 `protobuf:"bytes,7,opt,name=entry_price,json=entryPrice,proto3" json:"entry_price,omitempty"`
	MarkPrice         string                 `protobuf:"bytes,8,opt,name=mark_price,json=markPrice,proto3" json:"mark_price,omitempty"`
	ObservedAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	AgentId           uint64                 `protobuf:"varint,10,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ExchangeAccountId uint64                 `protobuf:"varint,11,opt,name=exchange_account_id,json=exchangeAccountId,proto3" json:"exchange_account_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpsertPositionRequest) Reset() {
	*x = UpsertPositionRequest{}
	mi := &file_hedging_v1_hedging_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertPositionRequest) ProtoMessage() {}

func (x *UpsertPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hedging_v1_hedging_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertPositionRequest.ProtoReflect.Descriptor instead.
func (*UpsertPositionRequest) Descriptor() ([]byte, []int) {
	return file_hedging_v1_hedging_proto_rawDescGZIP(), []int{1}
}

func (x *UpsertPositionRequest) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *UpsertPositionRequest) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *UpsertPositionRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *UpsertPositionRequest) GetPositionSide() string {
	if x != nil {
		return x.PositionSide
	}
	return ""
}

func (x *UpsertPositionRequest) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *UpsertPositionRequest) GetNotionalUsdt() string {
	if x != nil {
		return x.NotionalUsdt
	}
	return ""
}

func (x *UpsertPositionRequest) GetEntryPrice() string {
	if x != nil {
		return x.EntryPrice
	}
	return ""
}

func (x *UpsertPositionRequest) GetMarkPrice() string {
	if x != nil {
		return x.MarkPrice
	}
	return ""
}

func (x *UpsertPositionRequest) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *UpsertPositionRequest) GetAgentId() uint64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *UpsertPositionRequest) GetExchangeAccountId() uint64 {
	if x != nil {
		return x.ExchangeAccountId
	}
	return 0
}

type RunHedgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigId      uint64                 `protobuf:"varint,1,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunHedgeRequest) Reset() {
	*x = RunHedgeRequest{}
	mi := &file_hedging_v1_hedging_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunHedgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunHedgeRequest) ProtoMessage() {}

func (x *RunHedgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hedging_v1_hedging_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunHedgeRequest.ProtoReflect.Descriptor instead.
func (*RunHedgeRequest) Descriptor() ([]byte, []int) {
	return file_hedging_v1_hedging_proto_rawDescGZIP(), []int{2}
}

func (x *RunHedgeRequest) GetConfigId() uint64 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

func (x *RunHedgeRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RunHedgeRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type EnqueueHedgeRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Queue         string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	MaxRetry      int32                  `protobuf:"varint,5,opt,name=max_retry,json=maxRetry,proto3" json:"max_retry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueHedgeRunResponse) Reset() {
	*x = EnqueueHedgeRunResponse{}
	mi := &file_hedging_v1_hedging_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueHedgeRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueHedgeRunResponse) ProtoMessage() {}

func (x *EnqueueHedgeRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hedging_v1_hedging_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueHedgeRunResponse.ProtoReflect.Descriptor instead.
func (*EnqueueHedgeRunResponse) Descriptor() ([]byte, []int) {
	return file_hedging_v1_hedging_proto_rawDescGZIP(), []int{3}
}

func (x *EnqueueHedgeRunResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EnqueueHedgeRunResponse) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *EnqueueHedgeRunResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EnqueueHedgeRunResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *EnqueueHedgeRunResponse) GetMaxRetry() int32 {
	if x != nil {
		return x.MaxRetry
	}
	return 0
}

type RunHedgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigId      uint64                 `protobuf:"varint,1,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	Exposure      *ExposureSnapshot      `protobuf:"bytes,2,opt,name=exposure,proto3" json:"exposure,omitempty"`
	Position      *PositionSnapshot      `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Decision      *HedgeDecision         `protobuf:"bytes,4,opt,name=decision,proto3" json:"decision,omitempty"`
	OrderPlan     *OrderPlan             `protobuf:"bytes,5,opt,name=order_plan,json=orderPlan,proto3" json:"order_plan,omitempty"`
	Execution     *OrderExecution        `protobuf:"bytes,6,opt,name=execution,proto3" json:"execution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunHedgeResponse) Reset() {
	*x = RunHedgeResponse{}
	mi := &file_hedging_v1_hedging_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunHedgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunHedgeResponse) ProtoMessage() {}

func (x *RunHedgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hedging_v1_hedging_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunHedgeResponse.ProtoReflect.Descriptor instead.
func (*RunHedgeResponse) Descriptor() ([]byte, []int) {
	return file_hedging_v1_hedging_proto_rawDescGZIP(), []int{4}
}

func (x *RunHedgeResponse) GetConfigId() uint64 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

func (x *RunHedgeResponse) GetExposure() *ExposureSnapshot {
	if x != nil {
		return x.Exposure
	}
	return nil
}

func (x *RunHedgeResponse) GetPosition() *PositionSnapshot {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *RunHedgeResponse) GetDecision() *HedgeDecision {
	if x != nil {
		return x.Decision
	}
	return nil
}

func (x *RunHedgeResponse) GetOrderPlan() *OrderPlan {
	if x != nil {
		return x.OrderPlan
	}
	return nil
}

func (x *RunHedgeResponse) GetExecution() *OrderExecution {
	if x != nil {
		return x.Execution
	}
	return nil
}

type ExposureSnapshot struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Source          string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Symbol          string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	NetQuantity     string                 `protobuf:"bytes,4,opt,name=net_quantity,json=netQuantity,proto3" json:"net_quantity,omitempty"`
	NetNotionalUsdt string                 `protobuf:"bytes,5,opt,name=net_notional_usdt,json=netNotionalUsdt,proto3" json:"net_notional_usdt,omitempty"`
	MarkPrice       string                 `protobuf:"bytes,6,opt,name=mark_price,json=markPrice,proto3" json:"mark_price,omitempty"`
	ObservedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	AgentId         uint64                 `protobuf:"varint,10,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExposureSnapshot) Reset() {
	*x = ExposureSnapshot{}
	mi := &file_hedging_v1_hedging_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExposureSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExposureSnapshot) ProtoMessage() {}

func (x *ExposureSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_hedging_v1_hedging_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExposureSnapshot.ProtoReflect.Descriptor instead.
func (*ExposureSnapshot) Descriptor() ([]byte, []int) {
	return file_hedging_v1_hedging_proto_rawDescGZIP(), []int{5}
}

func (x *ExposureSnapshot) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ExposureSnapshot) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ExposureSnapshot) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *ExposureSnapshot) GetNetQuantity() string {
	if x != nil {
		return x.NetQuantity
	}
	return ""
}

func (x *ExposureSnapshot) GetNetNotionalUsdt() string {
	if x != nil {
		return x.NetNotionalUsdt
	}
	return ""
}

func (x *ExposureSnapshot) GetMarkPrice() string {
	if x != nil {
		return x.MarkPrice
	}
	return ""
}

func (x *ExposureSnapshot) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *ExposureSnapshot) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ExposureSnapshot) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ExposureSnapshot) GetAgentId() uint64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

type PositionSnapshot struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Exchange          string                 `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	AccountName       string                 `protobuf:"bytes,3,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	Symbol            string                 `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	PositionSide      string                 `protobuf:"bytes,5,opt,name=position_side,json=positionSide,proto3" json:"position_side,omitempty"`
	Quantity          string                 `protobuf:"bytes,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	NotionalUsdt      string                 `protobuf:"bytes,7,opt,name=notional_usdt,json=notionalUsdt,proto3" json:"notional_usdt,omitempty"`
	EntryPrice        string                 `protobuf:"bytes,8,opt,name=entry_price,json=entryPrice,proto3" json:"entry_price,omitempty"`
	MarkPrice         string                 `protobuf:"bytes,9,opt,name=mark_price,json=markPrice,proto3" json:"mark_price,omitempty"`
	ObservedAt        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	AgentId           uint64                 `protobuf:"varint,13,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ExchangeAccountId uint64                 `protobuf:"varint,14,opt,name=exchange_account_id,json=exchangeAccountId,proto3" json:"exchange_account_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PositionSnapshot) Reset() {
	*x = PositionSnapshot{}
	mi := &file_hedging_v1_hedging_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionSnapshot) ProtoMessage() {}

func (x *PositionSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_hedging_v1_hedging_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionSnapshot.ProtoReflect.Descriptor instead.
func (*PositionSnapshot) Descriptor() ([]byte, []int) {
	return file_hedging_v1_hedging_proto_rawDescGZIP(), []int{6}
}

func (x *PositionSnapshot) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PositionSnapshot) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *PositionSnapshot) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *PositionSnapshot) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PositionSnapshot) GetPositionSide() string {
	if x != nil {
		return x.PositionSide
	}
	return ""
}

func (x *PositionSnapshot) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *PositionSnapshot) GetNotionalUsdt() string {
	if x != nil {
		return x.NotionalUsdt
	}
	return ""
}

func (x *PositionSnapshot) GetEntryPrice() string {
	if x != nil {
		return x.EntryPrice
	}
	return ""
}

func (x *PositionSnapshot) GetMarkPrice() string {
	if x != nil {
		return x.MarkPrice
	}
	return ""
}

func (x *PositionSnapshot) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *PositionSnapshot) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PositionSnapshot) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *PositionSnapshot) GetAgentId() uint64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *PositionSnapshot) GetExchangeAccountId() uint64 {
	if x != nil {
		return x.ExchangeAccountId
	}
	return 0
}

type HedgeDecision struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Action              string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Side                string                 `protobuf:"bytes,2,opt,name=side,proto3" json:"side,omitempty"`
	Symbol              string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	TargetNotionalUsdt  string                 `protobuf:"bytes,4,opt,name=target_notional_usdt,json=targetNotionalUsdt,proto3" json:"target_notional_usdt,omitempty"`
	CurrentNotionalUsdt string                 `protobuf:"bytes,5,opt,name=current_notional_usdt,json=currentNotionalUsdt,proto3" json:"current_notional_usdt,omitempty"`
	AdjustmentUsdt      string                 `protobuf:"bytes,6,opt,name=adjustment_usdt,json=adjustmentUsdt,proto3" json:"adjustment_usdt,omitempty"`
	OrderQuantity       string                 `protobuf:"bytes,7,opt,name=order_quantity,json=orderQuantity,proto3" json:"order_quantity,omitempty"`
	LimitPrice          string                 `protobuf:"bytes,8,opt,name=limit_price,json=limitPrice,proto3" json:"limit_price,omitempty"`
	ReduceOnly          bool                   `protobuf:"varint,9,opt,name=reduce_only,json=reduceOnly,proto3" json:"reduce_only,omitempty"`
	Reason              string                 `protobuf:"bytes,10,opt,name=reason,proto3" json:"reason,omitempty"`
	DryRun              bool                   `protobuf:"varint,11,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HedgeDecision) Reset() {
	*x = HedgeDecision{}
	mi := &file_hedging_v1_hedging_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HedgeDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HedgeDecision) ProtoMessage() {}

func (x *HedgeDecision) ProtoReflect() protoreflect.Message {
	mi := &file_hedging_v1_hedging_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HedgeDecision.ProtoReflect.Descriptor instead.
func (*HedgeDecision) Descriptor() ([]byte, []int) {
	return file_hedging_v1_hedging_proto_rawDescGZIP(), []int{7}
}

func (x *HedgeDecision) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *HedgeDecision) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *HedgeDecision) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *HedgeDecision) GetTargetNotionalUsdt() string {
	if x != nil {
		return x.TargetNotionalUsdt
	}
	return ""
}

func (x *HedgeDecision) GetCurrentNotionalUsdt() string {
	if x != nil {
		return x.CurrentNotionalUsdt
	}
	return ""
}

func (x *HedgeDecision) GetAdjustmentUsdt() string {
	if x != nil {
		return x.AdjustmentUsdt
	}
	return ""
}

func (x *HedgeDecision) GetOrderQuantity() string {
	if x != nil {
		return x.OrderQuantity
	}
	return ""
}

func (x *HedgeDecision) GetLimitPrice() string {
	if x != nil {
		return x.LimitPrice
	}
	return ""
}

func (x *HedgeDecision) GetReduceOnly() bool {
	if x != nil {
		return x.ReduceOnly
	}
	return false
}

func (x *HedgeDecision) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *HedgeDecision) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type OrderPlan struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	ConfigId       uint64                 `protobuf:"varint,3,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	Source         string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Exchange       string                 `protobuf:"bytes,5,opt,name=exchange,proto3" json:"exchange,omitempty"`
	AccountName    string                 `protobuf:"bytes,6,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	Symbol         string                 `protobuf:"bytes,7,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side           string                 `protobuf:"bytes,8,opt,name=side,proto3" json:"side,omitempty"`
	PositionSide   string                 `protobuf:"bytes,9,opt,name=position_side,json=positionSide,proto3" json:"position_side,omitempty"`
	OrderType      string                 `protobuf:"bytes,10,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	Quantity       string                 `protobuf:"bytes,11,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price          string                 `protobuf:"bytes,12,opt,name=price,proto3" json:"price,omitempty"`
	NotionalUsdt   string                 `protobuf:"bytes,13,opt,name=notional_usdt,json=notionalUsdt,proto3" json:"notional_usdt,omitempty"`
	ReduceOnly     bool                   `protobuf:"varint,14,opt,name=reduce_only,json=reduceOnly,proto3" json:"reduce_only,omitempty"`
	Reason         string                 `protobuf:"bytes,15,opt,name=reason,proto3" json:"reason,omitempty"`
	Status         string                 `protobuf:"bytes,16,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrderPlan) Reset() {
	*x = OrderPlan{}
	mi := &file_hedging_v1_hedging_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPlan) ProtoMessage() {}

func (x *OrderPlan) ProtoReflect() protoreflect.Message {
	mi := &file_hedging_v1_hedging_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPlan.ProtoReflect.Descriptor instead.
func (*OrderPlan) Descriptor() ([]byte, []int) {
	return file_hedging_v1_hedging_proto_rawDescGZIP(), []int{8}
}

func (x *OrderPlan) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderPlan) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *OrderPlan) GetConfigId() uint64 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

func (x *OrderPlan) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *OrderPlan) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *OrderPlan) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *OrderPlan) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OrderPlan) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *OrderPlan) GetPositionSide() string {
	if x != nil {
		return x.PositionSide
	}
	return ""
}

func (x *OrderPlan) GetOrderType() string {
	if x != nil {
		return x.OrderType
	}
	return ""
}

func (x *OrderPlan) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *OrderPlan) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *OrderPlan) GetNotionalUsdt() string {
	if x != nil {
		return x.NotionalUsdt
	}
	return ""
}

func (x *OrderPlan) GetReduceOnly() bool {
	if x != nil {
		return x.ReduceOnly
	}
	return false
}

func (x *OrderPlan) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *OrderPlan) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderPlan) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *OrderPlan) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type OrderExecution struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderPlanId     uint64                 `protobuf:"varint,2,opt,name=order_plan_id,json=orderPlanId,proto3" json:"order_plan_id,omitempty"`
	ExchangeOrderId string                 `protobuf:"bytes,3,opt,name=exchange_order_id,json=exchangeOrderId,proto3" json:"exchange_order_id,omitempty"`
	ClientOrderId   string                 `protobuf:"bytes,4,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty"`
	Status          string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	FilledQuantity  string                 `protobuf:"bytes,6,opt,name=filled_quantity,json=filledQuantity,proto3" json:"filled_quantity,omitempty"`
	AvgPrice        string                 `protobuf:"bytes,7,opt,name=avg_price,json=avgPrice,proto3" json:"avg_price,omitempty"`
	FeeUsdt         string                 `protobuf:"bytes,8,opt,name=fee_usdt,json=feeUsdt,proto3" json:"fee_usdt,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OrderExecution) Reset() {
	*x = OrderExecution{}
	mi := &file_hedging_v1_hedging_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderExecution) ProtoMessage() {}

func (x *OrderExecution) ProtoReflect() protoreflect.Message {
	mi := &file_hedging_v1_hedging_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderExecution.ProtoReflect.Descriptor instead.
func (*OrderExecution) Descriptor() ([]byte, []int) {
	return file_hedging_v1_hedging_proto_rawDescGZIP(), []int{9}
}

func (x *OrderExecution) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderExecution) GetOrderPlanId() uint64 {
	if x != nil {
		return x.OrderPlanId
	}
	return 0
}

func (x *OrderExecution) GetExchangeOrderId() string {
	if x != nil {
		return x.ExchangeOrderId
	}
	return ""
}

func (x *OrderExecution) GetClientOrderId() string {
	if x != nil {
		return x.ClientOrderId
	}
	return ""
}

func (x *OrderExecution) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderExecution) GetFilledQuantity() string {
	if x != nil {
		return x.FilledQuantity
	}
	return ""
}

func (x *OrderExecution) GetAvgPrice() string {
	if x != nil {
		return x.AvgPrice
	}
	return ""
}

func (x *OrderExecution) GetFeeUsdt() string {
	if x != nil {
		return x.FeeUsdt
	}
	return ""
}

func (x *OrderExecution) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *OrderExecution) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *OrderExecution) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_hedging_v1_hedging_proto protoreflect.FileDescriptor

const file_hedging_v1_hedging_proto_rawDesc = "" +
	"\n" +
	"\x18hedging/v1/hedging.proto\x12\n" +
	"hedging.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8d\x02\n" +
	"\x15UpsertExposureRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12!\n" +
	"\fnet_quantity\x18\x03 \x01(\tR\vnetQuantity\x12*\n" +
	"\x11net_notional_usdt\x18\x04 \x01(\tR\x0fnetNotionalUsdt\x12\x1d\n" +
	"\n" +
	"mark_price\x18\x05 \x01(\tR\tmarkPrice\x12;\n" +
	"\vobserved_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12\x19\n" +
	"\bagent_id\x18\a \x01(\x04R\aagentId\"\x9c\x03\n" +
	"\x15UpsertPositionRequest\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12!\n" +
	"\faccount_name\x18\x02 \x01(\tR\vaccountName\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12#\n" +
	"\rposition_side\x18\x04 \x01(\tR\fpositionSide\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\tR\bquantity\x12#\n" +
	"\rnotional_usdt\x18\x06 \x01(\tR\fnotionalUsdt\x12\x1f\n" +
	"\ventry_price\x18\a \x01(\tR\n" +
	"entryPrice\x12\x1d\n" +
	"\n" +
	"mark_price\x18\b \x01(\tR\tmarkPrice\x12;\n" +
	"\vobserved_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12\x19\n" +
	"\bagent_id\x18\n" +
	" \x01(\x04R\aagentId\x12.\n" +
	"\x13exchange_account_id\x18\v \x01(\x04R\x11exchangeAccountId\"^\n" +
	"\x0fRunHedgeRequest\x12\x1b\n" +
	"\tconfig_id\x18\x01 \x01(\x04R\bconfigId\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\"\x86\x01\n" +
	"\x17EnqueueHedgeRunResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x1b\n" +
	"\tmax_retry\x18\x05 \x01(\x05R\bmaxRetry\"\xca\x02\n" +
	"\x10RunHedgeResponse\x12\x1b\n" +
	"\tconfig_id\x18\x01 \x01(\x04R\bconfigId\x128\n" +
	"\bexposure\x18\x02 \x01(\v2\x1c.hedging.v1.ExposureSnapshotR\bexposure\x128\n" +
	"\bposition\x18\x03 \x01(\v2\x1c.hedging.v1.PositionSnapshotR\bposition\x125\n" +
	"\bdecision\x18\x04 \x01(\v2\x19.hedging.v1.HedgeDecisionR\bdecision\x124\n" +
	"\n" +
	"order_plan\x18\x05 \x01(\v2\x15.hedging.v1.OrderPlanR\torderPlan\x128\n" +
	"\texecution\x18\x06 \x01(\v2\x1a.hedging.v1.OrderExecutionR\texecution\"\x8e\x03\n" +
	"\x10ExposureSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12!\n" +
	"\fnet_quantity\x18\x04 \x01(\tR\vnetQuantity\x12*\n" +
	"\x11net_notional_usdt\x18\x05 \x01(\tR\x0fnetNotionalUsdt\x12\x1d\n" +
	"\n" +
	"mark_price\x18\x06 \x01(\tR\tmarkPrice\x12;\n" +
	"\vobserved_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x19\n" +
	"\bagent_id\x18\n" +
	" \x01(\x04R\aagentId\"\x9d\x04\n" +
	"\x10PositionSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\bexchange\x18\x02 \x01(\tR\bexchange\x12!\n" +
	"\faccount_name\x18\x03 \x01(\tR\vaccountName\x12\x16\n" +
	"\x06symbol\x18\x04 \x01(\tR\x06symbol\x12#\n" +
	"\rposition_side\x18\x05 \x01(\tR\fpositionSide\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\tR\bquantity\x12#\n" +
	"\rnotional_usdt\x18\a \x01(\tR\fnotionalUsdt\x12\x1f\n" +
	"\ventry_price\x18\b \x01(\tR\n" +
	"entryPrice\x12\x1d\n" +
	"\n" +
	"mark_price\x18\t \x01(\tR\tmarkPrice\x12;\n" +
	"\vobserved_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x19\n" +
	"\bagent_id\x18\r \x01(\x04R\aagentId\x12.\n" +
	"\x13exchange_account_id\x18\x0e \x01(\x04R\x11exchangeAccountId\"\xfc\x02\n" +
	"\rHedgeDecision\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x12\n" +
	"\x04side\x18\x02 \x01(\tR\x04side\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x120\n" +
	"\x14target_notional_usdt\x18\x04 \x01(\tR\x12targetNotionalUsdt\x122\n" +
	"\x15current_notional_usdt\x18\x05 \x01(\tR\x13currentNotionalUsdt\x12'\n" +
	"\x0fadjustment_usdt\x18\x06 \x01(\tR\x0eadjustmentUsdt\x12%\n" +
	"\x0eorder_quantity\x18\a \x01(\tR\rorderQuantity\x12\x1f\n" +
	"\vlimit_price\x18\b \x01(\tR\n" +
	"limitPrice\x12\x1f\n" +
	"\vreduce_only\x18\t \x01(\bR\n" +
	"reduceOnly\x12\x16\n" +
	"\x06reason\x18\n" +
	" \x01(\tR\x06reason\x12\x17\n" +
	"\adry_run\x18\v \x01(\bR\x06dryRun\"\xc6\x04\n" +
	"\tOrderPlan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12\x1b\n" +
	"\tconfig_id\x18\x03 \x01(\x04R\bconfigId\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x1a\n" +
	"\bexchange\x18\x05 \x01(\tR\bexchange\x12!\n" +
	"\faccount_name\x18\x06 \x01(\tR\vaccountName\x12\x16\n" +
	"\x06symbol\x18\a \x01(\tR\x06symbol\x12\x12\n" +
	"\x04side\x18\b \x01(\tR\x04side\x12#\n" +
	"\rposition_side\x18\t \x01(\tR\fpositionSide\x12\x1d\n" +
	"\n" +
	"order_type\x18\n" +
	" \x01(\tR\torderType\x12\x1a\n" +
	"\bquantity\x18\v \x01(\tR\bquantity\x12\x14\n" +
	"\x05price\x18\f \x01(\tR\x05price\x12#\n" +
	"\rnotional_usdt\x18\r \x01(\tR\fnotionalUsdt\x12\x1f\n" +
	"\vreduce_only\x18\x0e \x01(\bR\n" +
	"reduceOnly\x12\x16\n" +
	"\x06reason\x18\x0f \x01(\tR\x06reason\x12\x16\n" +
	"\x06status\x18\x10 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xac\x03\n" +
	"\x0eOrderExecution\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\"\n" +
	"\rorder_plan_id\x18\x02 \x01(\x04R\vorderPlanId\x12*\n" +
	"\x11exchange_order_id\x18\x03 \x01(\tR\x0fexchangeOrderId\x12&\n" +
	"\x0fclient_order_id\x18\x04 \x01(\tR\rclientOrderId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12'\n" +
	"\x0ffilled_quantity\x18\x06 \x01(\tR\x0efilledQuantity\x12\x1b\n" +
	"\tavg_price\x18\a \x01(\tR\bavgPrice\x12\x19\n" +
	"\bfee_usdt\x18\b \x01(\tR\afeeUsdt\x12#\n" +
	"\rerror_message\x18\t \x01(\tR\ferrorMessage\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\x9a\x03\n" +
	"\x0eHedgingService\x12Q\n" +
	"\x0eUpsertExposure\x12!.hedging.v1.UpsertExposureRequest\x1a\x1c.hedging.v1.ExposureSnapshot\x12Q\n" +
	"\x0eUpsertPosition\x12!.hedging.v1.UpsertPositionRequest\x1a\x1c.hedging.v1.PositionSnapshot\x12E\n" +
	"\bRunHedge\x12\x1b.hedging.v1.RunHedgeRequest\x1a\x1c.hedging.v1.RunHedgeResponse\x12F\n" +
	"\tExitHedge\x12\x1b.hedging.v1.RunHedgeRequest\x1a\x1c.hedging.v1.RunHedgeResponse\x12S\n" +
	"\x0fEnqueueHedgeRun\x12\x1b.hedging.v1.RunHedgeRequest\x1a#.hedging.v1.EnqueueHedgeRunResponseBJZHgithub.com/zhangjinteng/6mm-hedging-bot/internal/pb/hedging/v1;hedgingv1b\x06proto3"

var (
	file_hedging_v1_hedging_proto_rawDescOnce sync.Once
	file_hedging_v1_hedging_proto_rawDescData []byte
)

func file_hedging_v1_hedging_proto_rawDescGZIP() []byte {
	file_hedging_v1_hedging_proto_rawDescOnce.Do(func() {
		file_hedging_v1_hedging_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hedging_v1_hedging_proto_rawDesc), len(file_hedging_v1_hedging_proto_rawDesc)))
	})
	return file_hedging_v1_hedging_proto_rawDescData
}

var file_hedging_v1_hedging_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_hedging_v1_hedging_proto_goTypes = []any{
	(*UpsertExposureRequest)(nil),   // 0: hedging.v1.UpsertExposureRequest
	(*UpsertPositionRequest)(nil),   // 1: hedging.v1.UpsertPositionRequest
	(*RunHedgeRequest)(nil),         // 2: hedging.v1.RunHedgeRequest
	(*EnqueueHedgeRunResponse)(nil), // 3: hedging.v1.EnqueueHedgeRunResponse
	(*RunHedgeResponse)(nil),        // 4: hedging.v1.RunHedgeResponse
	(*ExposureSnapshot)(nil),        // 5: hedging.v1.ExposureSnapshot
	(*PositionSnapshot)(nil),        // 6: hedging.v1.PositionSnapshot
	(*HedgeDecision)(nil),           // 7: hedging.v1.HedgeDecision
	(*OrderPlan)(nil),               // 8: hedging.v1.OrderPlan
	(*OrderExecution)(nil),          // 9: hedging.v1.OrderExecution
	(*timestamppb.Timestamp)(nil),   // 10: google.protobuf.Timestamp
}
var file_hedging_v1_hedging_proto_depIdxs = []int32{
	10, // 0: hedging.v1.UpsertExposureRequest.observed_at:type_name -> google.protobuf.Timestamp
	10, // 1: hedging.v1.UpsertPositionRequest.observed_at:type_name -> google.protobuf.Timestamp
	5,  // 2: hedging.v1.RunHedgeResponse.exposure:type_name -> hedging.v1.ExposureSnapshot
	6,  // 3: hedging.v1.RunHedgeResponse.position:type_name -> hedging.v1.PositionSnapshot
	7,  // 4: hedging.v1.RunHedgeResponse.decision:type_name -> hedging.v1.HedgeDecision
	8,  // 5: hedging.v1.RunHedgeResponse.order_plan:type_name -> hedging.v1.OrderPlan
	9,  // 6: hedging.v1.RunHedgeResponse.execution:type_name -> hedging.v1.OrderExecution
	10, // 7: hedging.v1.ExposureSnapshot.observed_at:type_name -> google.protobuf.Timestamp
	10, // 8: hedging.v1.ExposureSnapshot.created_at:type_name -> google.protobuf.Timestamp
	10, // 9: hedging.v1.ExposureSnapshot.updated_at:type_name -> google.protobuf.Timestamp
	10, // 10: hedging.v1.PositionSnapshot.observed_at:type_name -> google.protobuf.Timestamp
	10, // 11: hedging.v1.PositionSnapshot.created_at:type_name -> google.protobuf.Timestamp
	10, // 12: hedging.v1.PositionSnapshot.updated_at:type_name -> google.protobuf.Timestamp
	10, // 13: hedging.v1.OrderPlan.created_at:type_name -> google.protobuf.Timestamp
	10, // 14: hedging.v1.OrderPlan.updated_at:type_name -> google.protobuf.Timestamp
	10, // 15: hedging.v1.OrderExecution.created_at:type_name -> google.protobuf.Timestamp
	10, // 16: hedging.v1.OrderExecution.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 17: hedging.v1.HedgingService.UpsertExposure:input_type -> hedging.v1.UpsertExposureRequest
	1,  // 18: hedging.v1.HedgingService.UpsertPosition:input_type -> hedging.v1.UpsertPositionRequest
	2,  // 19: hedging.v1.HedgingService.RunHedge:input_type -> hedging.v1.RunHedgeRequest
	2,  // 20: hedging.v1.HedgingService.ExitHedge:input_type -> hedging.v1.RunHedgeRequest
	2,  // 21: hedging.v1.HedgingService.EnqueueHedgeRun:input_type -> hedging.v1.RunHedgeRequest
	5,  // 22: hedging.v1.HedgingService.UpsertExposure:output_type -> hedging.v1.ExposureSnapshot
	6,  // 23: hedging.v1.HedgingService.UpsertPosition:output_type -> hedging.v1.PositionSnapshot
	4,  // 24: hedging.v1.HedgingService.RunHedge:output_type -> hedging.v1.RunHedgeResponse
	4,  // 25: hedging.v1.HedgingService.ExitHedge:output_type -> hedging.v1.RunHedgeResponse
	3,  // 26: hedging.v1.HedgingService.EnqueueHedgeRun:output_type -> hedging.v1.EnqueueHedgeRunResponse
	22, // [22:27] is the sub-list for method output_type
	17, // [17:22] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_hedging_v1_hedging_proto_init() }
func file_hedging_v1_hedging_proto_init() {
	if File_hedging_v1_hedging_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hedging_v1_hedging_proto_rawDesc), len(file_hedging_v1_hedging_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hedging_v1_hedging_proto_goTypes,
		DependencyIndexes: file_hedging_v1_hedging_proto_depIdxs,
		MessageInfos:      file_hedging_v1_hedging_proto_msgTypes,
	}.Build()
	File_hedging_v1_hedging_proto = out.File
	file_hedging_v1_hedging_proto_goTypes = nil
	file_hedging_v1_hedging_proto_depIdxs = nil
}
